// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ps.proto
#ifndef GRPC_ps_2eproto__INCLUDED
#define GRPC_ps_2eproto__INCLUDED

#include "ps.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace ps {

class Service final {
 public:
  static constexpr char const* service_full_name() {
    return "ps.Service";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status batch_pull(::grpc::ClientContext* context, const ::ps::BatchRequest& request, ::ps::BatchResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ps::BatchResponse>> Asyncbatch_pull(::grpc::ClientContext* context, const ::ps::BatchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ps::BatchResponse>>(Asyncbatch_pullRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ps::BatchResponse>> PrepareAsyncbatch_pull(::grpc::ClientContext* context, const ::ps::BatchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ps::BatchResponse>>(PrepareAsyncbatch_pullRaw(context, request, cq));
    }
    virtual ::grpc::Status pull(::grpc::ClientContext* context, const ::ps::SingleRequest& request, ::ps::SingleResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ps::SingleResponse>> Asyncpull(::grpc::ClientContext* context, const ::ps::SingleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ps::SingleResponse>>(AsyncpullRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ps::SingleResponse>> PrepareAsyncpull(::grpc::ClientContext* context, const ::ps::SingleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ps::SingleResponse>>(PrepareAsyncpullRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void batch_pull(::grpc::ClientContext* context, const ::ps::BatchRequest* request, ::ps::BatchResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void batch_pull(::grpc::ClientContext* context, const ::ps::BatchRequest* request, ::ps::BatchResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void batch_pull(::grpc::ClientContext* context, const ::ps::BatchRequest* request, ::ps::BatchResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void pull(::grpc::ClientContext* context, const ::ps::SingleRequest* request, ::ps::SingleResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void pull(::grpc::ClientContext* context, const ::ps::SingleRequest* request, ::ps::SingleResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void pull(::grpc::ClientContext* context, const ::ps::SingleRequest* request, ::ps::SingleResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ps::BatchResponse>* Asyncbatch_pullRaw(::grpc::ClientContext* context, const ::ps::BatchRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ps::BatchResponse>* PrepareAsyncbatch_pullRaw(::grpc::ClientContext* context, const ::ps::BatchRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ps::SingleResponse>* AsyncpullRaw(::grpc::ClientContext* context, const ::ps::SingleRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ps::SingleResponse>* PrepareAsyncpullRaw(::grpc::ClientContext* context, const ::ps::SingleRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status batch_pull(::grpc::ClientContext* context, const ::ps::BatchRequest& request, ::ps::BatchResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ps::BatchResponse>> Asyncbatch_pull(::grpc::ClientContext* context, const ::ps::BatchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ps::BatchResponse>>(Asyncbatch_pullRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ps::BatchResponse>> PrepareAsyncbatch_pull(::grpc::ClientContext* context, const ::ps::BatchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ps::BatchResponse>>(PrepareAsyncbatch_pullRaw(context, request, cq));
    }
    ::grpc::Status pull(::grpc::ClientContext* context, const ::ps::SingleRequest& request, ::ps::SingleResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ps::SingleResponse>> Asyncpull(::grpc::ClientContext* context, const ::ps::SingleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ps::SingleResponse>>(AsyncpullRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ps::SingleResponse>> PrepareAsyncpull(::grpc::ClientContext* context, const ::ps::SingleRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ps::SingleResponse>>(PrepareAsyncpullRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void batch_pull(::grpc::ClientContext* context, const ::ps::BatchRequest* request, ::ps::BatchResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void batch_pull(::grpc::ClientContext* context, const ::ps::BatchRequest* request, ::ps::BatchResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void batch_pull(::grpc::ClientContext* context, const ::ps::BatchRequest* request, ::ps::BatchResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void pull(::grpc::ClientContext* context, const ::ps::SingleRequest* request, ::ps::SingleResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void pull(::grpc::ClientContext* context, const ::ps::SingleRequest* request, ::ps::SingleResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void pull(::grpc::ClientContext* context, const ::ps::SingleRequest* request, ::ps::SingleResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ps::BatchResponse>* Asyncbatch_pullRaw(::grpc::ClientContext* context, const ::ps::BatchRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ps::BatchResponse>* PrepareAsyncbatch_pullRaw(::grpc::ClientContext* context, const ::ps::BatchRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ps::SingleResponse>* AsyncpullRaw(::grpc::ClientContext* context, const ::ps::SingleRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ps::SingleResponse>* PrepareAsyncpullRaw(::grpc::ClientContext* context, const ::ps::SingleRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_batch_pull_;
    const ::grpc::internal::RpcMethod rpcmethod_pull_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status batch_pull(::grpc::ServerContext* context, const ::ps::BatchRequest* request, ::ps::BatchResponse* response);
    virtual ::grpc::Status pull(::grpc::ServerContext* context, const ::ps::SingleRequest* request, ::ps::SingleResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_batch_pull : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_batch_pull() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_batch_pull() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status batch_pull(::grpc::ServerContext* /*context*/, const ::ps::BatchRequest* /*request*/, ::ps::BatchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestbatch_pull(::grpc::ServerContext* context, ::ps::BatchRequest* request, ::grpc::ServerAsyncResponseWriter< ::ps::BatchResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_pull : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_pull() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_pull() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status pull(::grpc::ServerContext* /*context*/, const ::ps::SingleRequest* /*request*/, ::ps::SingleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestpull(::grpc::ServerContext* context, ::ps::SingleRequest* request, ::grpc::ServerAsyncResponseWriter< ::ps::SingleResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_batch_pull<WithAsyncMethod_pull<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_batch_pull : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_batch_pull() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ps::BatchRequest, ::ps::BatchResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::ps::BatchRequest* request, ::ps::BatchResponse* response) { return this->batch_pull(context, request, response); }));}
    void SetMessageAllocatorFor_batch_pull(
        ::grpc::experimental::MessageAllocator< ::ps::BatchRequest, ::ps::BatchResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ps::BatchRequest, ::ps::BatchResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_batch_pull() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status batch_pull(::grpc::ServerContext* /*context*/, const ::ps::BatchRequest* /*request*/, ::ps::BatchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* batch_pull(
      ::grpc::CallbackServerContext* /*context*/, const ::ps::BatchRequest* /*request*/, ::ps::BatchResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* batch_pull(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::ps::BatchRequest* /*request*/, ::ps::BatchResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_pull : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_pull() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::ps::SingleRequest, ::ps::SingleResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::ps::SingleRequest* request, ::ps::SingleResponse* response) { return this->pull(context, request, response); }));}
    void SetMessageAllocatorFor_pull(
        ::grpc::experimental::MessageAllocator< ::ps::SingleRequest, ::ps::SingleResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ps::SingleRequest, ::ps::SingleResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_pull() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status pull(::grpc::ServerContext* /*context*/, const ::ps::SingleRequest* /*request*/, ::ps::SingleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* pull(
      ::grpc::CallbackServerContext* /*context*/, const ::ps::SingleRequest* /*request*/, ::ps::SingleResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* pull(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::ps::SingleRequest* /*request*/, ::ps::SingleResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_batch_pull<ExperimentalWithCallbackMethod_pull<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_batch_pull<ExperimentalWithCallbackMethod_pull<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_batch_pull : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_batch_pull() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_batch_pull() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status batch_pull(::grpc::ServerContext* /*context*/, const ::ps::BatchRequest* /*request*/, ::ps::BatchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_pull : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_pull() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_pull() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status pull(::grpc::ServerContext* /*context*/, const ::ps::SingleRequest* /*request*/, ::ps::SingleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_batch_pull : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_batch_pull() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_batch_pull() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status batch_pull(::grpc::ServerContext* /*context*/, const ::ps::BatchRequest* /*request*/, ::ps::BatchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestbatch_pull(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_pull : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_pull() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_pull() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status pull(::grpc::ServerContext* /*context*/, const ::ps::SingleRequest* /*request*/, ::ps::SingleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void Requestpull(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_batch_pull : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_batch_pull() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->batch_pull(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_batch_pull() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status batch_pull(::grpc::ServerContext* /*context*/, const ::ps::BatchRequest* /*request*/, ::ps::BatchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* batch_pull(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* batch_pull(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_pull : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_pull() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->pull(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_pull() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status pull(::grpc::ServerContext* /*context*/, const ::ps::SingleRequest* /*request*/, ::ps::SingleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* pull(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* pull(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_batch_pull : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_batch_pull() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ps::BatchRequest, ::ps::BatchResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ps::BatchRequest, ::ps::BatchResponse>* streamer) {
                       return this->Streamedbatch_pull(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_batch_pull() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status batch_pull(::grpc::ServerContext* /*context*/, const ::ps::BatchRequest* /*request*/, ::ps::BatchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedbatch_pull(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ps::BatchRequest,::ps::BatchResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_pull : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_pull() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ps::SingleRequest, ::ps::SingleResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ps::SingleRequest, ::ps::SingleResponse>* streamer) {
                       return this->Streamedpull(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_pull() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status pull(::grpc::ServerContext* /*context*/, const ::ps::SingleRequest* /*request*/, ::ps::SingleResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status Streamedpull(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ps::SingleRequest,::ps::SingleResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_batch_pull<WithStreamedUnaryMethod_pull<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_batch_pull<WithStreamedUnaryMethod_pull<Service > > StreamedService;
};

}  // namespace ps


#endif  // GRPC_ps_2eproto__INCLUDED
